#scaden predict --model_dir /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/scRNA/simulation_onlyNormalized/processed_simulation_data/Skin_Cancer/model /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/h5ad/SkinCancer_RNA_geneSubset.txt --outname /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/h5ad/SkinCancer_RNA_geneSubset_prediction.txt

#scaden predict --model_dir /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/scRNA/simulation_onlyNormalized/lung_cancer_all_oncoKB_19/processed_simulation_data/Lung_Cancer/model /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/h5ad/lung_cancer_all_oncoKB_19/LungCancer_RNA_geneSubset.txt --outname /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/h5ad/lung_cancer_all_oncoKB_19/LungCancer_RNA_geneSubset_prediction.txt

#scaden predict --model_dir /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/scRNA/simulation_onlyNormalized/lung_cancer_oncoKB_with_drugs_11/processed_simulation_data/Lung_Cancer/model /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/h5ad/lung_cancer_oncoKB_with_drugs_11/LungCancer_RNA_geneSubset.txt --outname /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/h5ad/lung_cancer_oncoKB_with_drugs_11/LungCancer_RNA_geneSubset_prediction.txt

#scaden predict --model_dir /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/scRNA/simulation_onlyNormalized/lung_cancer_all_oncoKB_mut_and_CGC_genes_30/processed_simulation_data/Lung_Cancer/model /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/h5ad/lung_cancer_all_oncoKB_mut_and_CGC_genes_30/LungCancer_RNA_geneSubset.txt --outname /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/h5ad/lung_cancer_all_oncoKB_mut_and_CGC_genes_30/LungCancer_RNA_geneSubset_prediction.txt

scaden predict --model_dir /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/scRNA/simulation_onlyNormalized/lung_cancer_all_oncoKB_19/processed_simulation_data/Lung_Cancer/model /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/RNA/lung_cancer_all_oncoKB_19/LungCancer_RNA_overlapped_genes_geneSubset.txt --outname /home/CBBI/hsuy1/projects/drugResponse/data/ICIBM_2023/TCGA/processed_data/RNA/lung_cancer_all_oncoKB_19/LungCancer_RNA_overlapped_genes_geneSubset_prediction.txt
