time python3 9-3_sub.all_mutations_BileDuctCancer.py
time python3 9-3_sub.all_mutations_BladderCancer.py
time python3 9-3_sub.all_mutations_BrainCancer.py
time python3 9-3_sub.all_mutations_BreastCancer.py
time python3 9-3_sub.all_mutations_ColonColorectalCancer.py
time python3 9-3_sub.all_mutations_EsophagealCancer.py
time python3 9-3_sub.all_mutations_EndometrialUterineCancer.py
time python3 9-3_sub.all_mutations_GastricCancer.py
time python3 9-3_sub.all_mutations_HeadandNeckCancer.py
time python3 9-3_sub.all_mutations_KidneyCancer.py
time python3 9-3_sub.all_mutations_LiverCancer.py
time python3 9-3_sub.all_mutations_LungCancer.py
time python3 9-3_sub.all_mutations_OvarianCancer.py
time python3 9-3_sub.all_mutations_PancreaticCancer.py
time python3 9-3_sub.all_mutations_ProstateCancer.py
time python3 9-3_sub.all_mutations_Sarcoma.py
time python3 9-3_sub.all_mutations_SkinCancer.py
time python3 9-3_sub.all_mutations_ThyroidCancer.py